### ISSUE TITLE
Epanechnikov kernel estimator

### ISSUE THREAD

**Issue by zedomel** [d3/d3-contour#19]
Is there any way to change kernel function of densityContour?

I would like to use Epanechnikov kernel, not the Gaussian kernel as documentation says. Any way to achieve this?

thanks.

**Comment by mbostock** [comment]
Doubtful. The current implementation uses a stack blur for fast computation (which works because the Gaussian kernel is [separable](https://en.wikipedia.org/wiki/Separable_filter)). Is Epanechinkov separable? In any case, you’re probably better off computing the grid on your own and then passing it to d3.contours rather than d3.contourDensity.

**Comment by zedomel** [comment]
Thanks for the quick answer @mbostock. Just after post the question I have realised that I can use d3.contours for that.

thanks.
