### ISSUE TITLE
GeoJSON Geometry which is generated by d3.contour displays wrong

### ISSUE THREAD

**Issue by chinesejar** [d3/d3-contour#37]
I generate geojson data using d3.contour, the data contains features of MultiPolygon. When I render it with fill layer, the small zoom it will merge, when I scale zoom, it will normal. Here is the example.

[demo](https://codesandbox.io/s/happy-pascal-uhv5k?fontsize=14&hidenavigation=1&theme=dark)

I found GeoJSON data has some continue and same coordinates, but I am not sure if it raised the error.

**Comment by mbostock** [comment]
Interesting. My guess is that this is a bug with mapbox-gl, which you’re using the render the generated GeoJSON. If you can reproduce this problem in d3-geo, or demonstrate that the generated GeoJSON is invalid (by describing how it is invalid, rather than as a rendering artifact), then I’d be happy to take a look.

**Comment by chinesejar** [comment]
I reproduce in d3-geo, when the properties.value of filter condition is 0 in line 24, the polygon is wrong. and other values like 0.25, 0.5 are right.

see example: [d3-geo demo](https://codesandbox.io/s/patient-platform-3jkr0?fontsize=14&hidenavigation=1&theme=dark)

can you fix the topology error?

**Comment by bumbeishvili** [comment]
This is definitely a mapbox issue, I came across with it as well

Here is a relevant mapbox issue - https://github.com/mapbox/mapbox-gl-js/issues/7023
